stages:
    - build
    - deploy

static_build:
  image: node:alpine
  stage: build
  variables:
    NODE_PATH: ./src
    PUBLIC_URL: /
    REACT_APP_COMMIT_ID: $CI_COMMIT_SHORT_SHA
    REACT_APP_BUILD_URL: $CI_PIPELINE_URL
  script:
    - echo $REACT_APP_API_KEY
    - npm ci
    - npm run build
  artifacts:
    paths:
      - ./build
  only:
    - develop

s3_upload:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  needs: ["static_build"]
  variables:
    GIT_STRATEGY: none
  script:
    - echo $S3_BUCKET
    - aws s3 sync --delete ./build  s3://$S3_BUCKET --exact-timestamps
  environment:
    name: staging
    url: https://$S3_BUCKET/
  only:
    - develop
